### ISSUE TITLE
Setting to prevent panes from closing when closing last file in pane

### ISSUE THREAD

**Issue by barberdt** [chemoish/atom-pane-layout#12]
You can totally tell me to screw off, but I feel like it would be great to have a setting that would allow you to keep panes open after closing the last file in that pane. At the moment, if you have three panes and you close the last file in the middle pane, that pane closes and you only have two (as opposed to three, with the middle pane being empty). Sometimes it's nice to clear your workspace to set yourself up for your next task, but it can be annoying to have to constantly reset your panes when doing so.

**Comment by chemoish** [comment]
Makes sense, I'll take a look at it when I have time. Busy with a rewrite.

Feel free to open PR.

**Comment by barberdt** [comment]
Perfect. I'll see if I can get around to attempting this.

**Comment by barberdt** [comment]
Excuse my nubbiness. Note the "Destroy Empty Panes" checkbox. As you were.


<img width="307" alt="screen shot 2015-07-21 at 11 48 58 pm" src="https://cloud.githubusercontent.com/assets/918406/8817601/2a33cdec-3003-11e5-9b15-318a468c6770.png">

**Comment by chemoish** [comment]
:+1:
