### ISSUE TITLE
Doesn't work on Atom 0.175.0 / Mac OSX 10.10.1

### ISSUE THREAD

**Issue by jimbru** [chemoish/atom-pane-layout#4]
Plugin installed, pressing `cmd-alt-<num>` has no discernible effect. Happy to offer further debugging info if you let me know where to find it (not an Atom developer myself).

**Comment by chemoish** [comment]
Let me double check tomorrow when I have my Mac. What version of the plugin are you using?

**Comment by jimbru** [comment]
Good question. It's v0.5.1.

**Comment by jonathandelgado** [comment]
Same issue on windows, it is due to the latest commit in which you changed the keybind.

https://github.com/chemoish/atom-pane-layout/blob/master/keymaps/pane-layout.cson#L10

There is not a `atom-text-editor` class, it is simply a tag. So removing the period before each mention would fix it.

**Comment by chemoish** [comment]
@jonathandelgado Thanks, I wonder why it is still working for me, but your right.

**Comment by chemoish** [comment]
After further investigation it seems that there is only an `atom-text-editor` available in an Editor. Which prevents you from interacting with the plugin outside of an Editor.

Still going to do more testing, but it might be enough just to remove that selector entirely.

**Comment by jonathandelgado** [comment]
@chemoish If you want to be able to use the keybinds outside the editor window, you can do the following for example:

```
".platform-win32, .platform-linux":
	"ctrl-alt-1": "pane-command"

".platform-darwin":
	"cmd-alt-1": "pane-command"
```

**Comment by chemoish** [comment]
Right, but there is an underlying issue regarding the change of utilizing
the workspace view—specifically pane view to pane models.

When I get a chance I'll continue to debug and push out working changes
that will utilize the non deprecated code.

Thanks.

**Comment by chemoish** [comment]
Fixed https://github.com/chemoish/atom-pane-layout/commit/006e5c908ca6b1c06ec6f73ebd5b14f29855d25f

**Comment by chemoish** [comment]
Opening a new issue.
