### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by keiter** [chemoish/atom-pane-layout#6]
Atom deprecation cop says:

> atom.workspaceView is no longer available.
> In most cases you will not need the view. See the Workspace docs for
> alternatives: https://atom.io/docs/api/latest/Workspace.
> If you do need the view, please use `atom.views.getView(atom.workspace)`,
> which returns an HTMLElement.
> ```
> Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:53:11)
> Object.activate (/Users/keiter/.atom/packages/pane-layout-plus/lib/pane-layout.coffee:5:9)
> ```

**Comment by chemoish** [comment]
@keiter I think it is a caching issue. Unless you are not up to date on the package.

Try: `Menu–View > Reload`

**Comment by keiter** [comment]
@chemoish I updated the package and reloaded the view, but I don't think that's the issue. If you look at the message and stackstrace again it says that `atom.workspaceView` is getting deprecated, and the points to lib/pane-layout.coffee in your plugin where that function is called several times.

**Comment by chemoish** [comment]
Fixed by https://github.com/chemoish/atom-pane-layout/commit/a0655e6b6e59ac9082dd39326a06d46bbc708513
