### ISSUE TITLE
Feature: Numbered navigation

### ISSUE THREAD

**Issue by mehcode** [chemoish/atom-pane-layout#9]
http://sublime-text-unofficial-documentation.readthedocs.org/en/latest/reference/keyboard_shortcuts_win.html#split-window

Any thoughts about supporting those shortcuts? I know you have the https://github.com/chemoish/atom-pane-move package but moving between is one thing, I'd like to move to an indexed pane. It wouldn't make sense (to me) to put the indexed move in that package as it has nothing to do with this simplified layout model.

**Comment by chemoish** [comment]
| # | Keypress | Command |
| --- | --- | --- |
| 1 | Ctrl + [NUM] |	Jump to group where num is 1-4 |
| 2 | Ctrl + ⇧ + [NUM] |	Move file to specified group where num is 1-4 |

Your looking for group jumping? Both look helpful.

**Comment by mehcode** [comment]
Yes. Looking for those two. Sorry for not being clear in the OP.

**Comment by chemoish** [comment]
Sounds good I'll try and look over them when I have time. Both seem useful, but I might split them into their respective packages.

**Comment by chemoish** [comment]
@mehcode So the feature itself is easy, but all the hotkeys are taken.

**Comment by mehcode** [comment]
Where are they taken? I'm looking in my resolver and I see `Ctrl + #` taken but it is scoped to tree view -- we should be able to scope ours to the editor window

**Comment by chemoish** [comment]
@mehcode Lol, sorry I had to run away mid comment. What hotkey did you have in mind?

**Comment by mehcode** [comment]
```
Ctrl+1 -> Puts focus on pane 1
Ctrl+2 -> Puts focus on pane 2
Ctrl+3 -> Puts focus on pane 3
Ctrl+4 -> Puts focus on pane 4
Ctrl+5 -> Puts focus on pane 5

Shift+Ctrl+1 -> Moves current file to pane 1
Shift+Ctrl+2 -> Moves current file to pane 2
Shift+Ctrl+3 -> Moves current file to pane 3
Shift+Ctrl+4 -> Moves current file to pane 4
Shift+Ctrl+5 -> Moves current file to pane 5
```

> Was your thought that you would like to be able to jump/move with using hotkeys only with your left hand? 

This. Similar to how sublime enables this.

**Comment by chemoish** [comment]
https://github.com/chemoish/atom-pane-layout/commit/8a818df08bdb53af97b14fa3f3380e8d4d2da08c

**Comment by chemoish** [comment]
Move fixed by https://github.com/chemoish/atom-pane-move/commit/e996bb3c1f2a9aec694e2f76848d773227d6cdaf

**Comment by mehcode** [comment]
You are a god among men.
